[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  # Set your production API URL here
  VITE_API_BASE_URL = "http://ec2-16-176-22-21.ap-southeast-2.compute.amazonaws.com:3000/api"
